---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- config/
- spec/
